# frozen_string_literal: true

source 'https://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'faker'
gem 'httparty'
gem 'pry'
gem 'rake'
gem 'rb-readline'
gem 'rspec'
gem 'rspec-expectations'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'assertthat-bdd'
